<?php

declare(strict_types=1);

namespace App\Domain\Audit\Enums;

/** Business Timeline event types (11 §34). */
enum BusinessAuditEvent: string
{
    case RECORD_CREATED = 'RECORD_CREATED';
    case DRAFT_UPDATED = 'DRAFT_UPDATED';
    case SUBMITTED = 'SUBMITTED';
    case RESULT_UPDATED = 'RESULT_UPDATED';
    case REVIEW_FORWARDED = 'REVIEW_FORWARDED';
    case REVIEW_RETURNED = 'REVIEW_RETURNED';
    case REVIEW_REJECTED = 'REVIEW_REJECTED';
    case APPROVAL_RETURNED_REVIEWER = 'APPROVAL_RETURNED_REVIEWER';
    case APPROVAL_RETURNED_REQUESTER = 'APPROVAL_RETURNED_REQUESTER';
    case APPROVAL_REJECTED = 'APPROVAL_REJECTED';
    case APPROVED = 'APPROVED';
    case REOPENED = 'REOPENED';
    case CANCELLED = 'CANCELLED';
    case ARCHIVED = 'ARCHIVED';
    case UNARCHIVED = 'UNARCHIVED';
    case ATTACHMENT_ADDED = 'ATTACHMENT_ADDED';
    case ATTACHMENT_REMOVED = 'ATTACHMENT_REMOVED';
}
