<?php

declare(strict_types=1);

namespace App\Domain\Audit\Enums;

/** Authentication, credential, session and administration security evidence (11 §37, 10 §15). */
enum SecurityAuditEvent: string
{
    case LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGIN_THROTTLED = 'LOGIN_THROTTLED';
    case LOGIN_ACCOUNT_DISABLED = 'LOGIN_ACCOUNT_DISABLED';
    case LOGOUT = 'LOGOUT';
    case SESSION_REVOKED = 'SESSION_REVOKED';
    case REAUTH_SUCCEEDED = 'REAUTH_SUCCEEDED';
    case REAUTH_FAILED = 'REAUTH_FAILED';
    case TEMPORARY_PASSWORD_REPLACED = 'TEMPORARY_PASSWORD_REPLACED';
    case USER_CREATED = 'USER_CREATED';
    case USER_UPDATED = 'USER_UPDATED';
    case USER_ENABLED = 'USER_ENABLED';
    case USER_DISABLED = 'USER_DISABLED';
    case PASSWORD_RESET = 'PASSWORD_RESET';
    case USER_ROLES_CHANGED = 'USER_ROLES_CHANGED';
    case USER_TEAM_CHANGED = 'USER_TEAM_CHANGED';
    case ROLE_CREATED = 'ROLE_CREATED';
    case ROLE_UPDATED = 'ROLE_UPDATED';
    case ROLE_PERMISSIONS_CHANGED = 'ROLE_PERMISSIONS_CHANGED';
    case TEAM_CREATED = 'TEAM_CREATED';
    case TEAM_UPDATED = 'TEAM_UPDATED';
    case TEAM_DEACTIVATED = 'TEAM_DEACTIVATED';
    case TEAM_REACTIVATED = 'TEAM_REACTIVATED';
    case PROTECTED_ACTION_DENIED = 'PROTECTED_ACTION_DENIED';
    case MALWARE_DETECTED = 'MALWARE_DETECTED';
    case MALWARE_SCAN_FAILED = 'MALWARE_SCAN_FAILED';
}
